CREATE TABLE [dbo].[SUPPLIER] (
    [SUPPLIERID] INT        NOT NULL,
    [USERNAME]   NCHAR (50) NOT NULL,
    [PASSWORD]   NCHAR (50) NOT NULL,
    [FULLNAME]   NCHAR (50) NOT NULL,
    [PICTURE]    NCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([SUPPLIERID] ASC)
);

