//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOOLE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int productID { get; set; }
        public int sub_catID { get; set; }
        public int SUPPLIERID { get; set; }
        public int manufID { get; set; }
        public string prodname { get; set; }
        public string prodimage { get; set; }
        public decimal price { get; set; }
        public string series { get; set; }
        public string model { get; set; }
        public int modelyear { get; set; }
        public string model_info { get; set; }
        public string techspecs { get; set; }
    }
}
