//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOOLE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CUSTOMER
    {
        public int CUSTOMERID { get; set; }
        
      
        [Required]
        public string USERNAME { get; set; }
        [Required]
        [MinLength(6)]
        public string PASSWORD { get; set; }
        public string FULLNAME { get; set; }
        public string PICTURE { get; set; }
    }
}
